name: Crash Report (v1)
description: Quickshell has crashed (old)
labels: ["unactionable"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to click the report button.
        At this point most of the worst issues in 0.2.1 and before have been fixed and we are
        preparing for a new release. Please do not submit this report.
  - type: checkboxes
    id: donotcheck
    attributes:
      label: Read the text above. Do not submit the report.
      options:
        - label: Yes I want this report to be deleted.
          required: true
