#include <qqmlcomponent.h>
#include <qqmlincubator.h>
#include "model.hpp"
#include "paths.hpp"
#include <qdatetime.h>
#include <qfilesystemwatcher.h>
#include <qicon.h>
#include "qmlglobal.hpp"
#include <qobjectdefs.h>
#include <qpair.h>
#include <qvariant.h>
#include "scan.hpp"
#include <qcoreapplication.h>
#include <qhash.h>
#include <qqmlcontext.h>
#include <qquickitem.h>
#include "reload.hpp"
#include <qfileinfo.h>
#include <qstring.h>
#include <qtenvironmentvariables.h>
#include "generation.hpp"
#include <qqmllist.h>
#include <algorithm>
#include <qdebug.h>
#include <qlist.h>
#include <qdir.h>
#include <qnamespace.h>
