#include <qdir.h>
#include <qhash.h>
#include <qlocalsocket.h>
#include <qmetaobject.h>
#include <qnamespace.h>
#include <qprocess.h>
#include <qqmlengine.h>
#include "../core/generation.hpp"
#include "../core/logcat.hpp"
#include "datastream.hpp"
#include "ipc.hpp"
#include <qcontainerfwd.h>
#include <qloggingcategory.h>
#include <qobjectdefs.h>
#include <qqmlinfo.h>
#include <qvariant.h>
#include <qlogging.h>
#include <qtmetamacros.h>
#include <qtypes.h>
#include <qobject.h>
#include <utility>
